services:
  #web:
  #  build:
  #    context: ./web
  #  env_file:
  #    - .env/web.env
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./web:/app
  #  depends_on:
  #    - api
  api:
    build:
      context: ./api
    env_file:
      - .env/api.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:17
    env_file:
      - .env/db.env
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  monitoring:
    image: prom/prometheus:v3.7.3
    env_file:
      - .env/monitoring.env
    volumes:
      - ./monitoring/config:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - api
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus/"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
  logging:
    image: grafana/grafana:main-ubuntu
    env_file:
      - .env/logging.env
    volumes:
      - grafana_data:/var/lib/grafana
    ports: 
      - "3001:3000"
    restart: always
    depends_on:
      - monitoring
volumes:
  prometheus_data:
  grafana_data: