---
- name: Deploy Node Exporter
  hosts: all
  vars:
    node_exporter_version: 1.10.2
  become: yes
  tasks:
    - name: Download and Extract Node Exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Move Node Exporter binary
      copy:
        src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter 
        mode: '0755'
        remote_src: yes

    - name: Add Service File For Node Exporter
      template:
        src: ./templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
      notify: Reload systemd

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
        daemon_reload: yes

  handlers:
    - name: Reload systemd 
      systemd:
        daemon_reload: yes
        
