---
-
  hosts: localhost
  vars:
    node_exporter_version: 1.10.2

  tasks:
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Move Node Exporter binary
      command: mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /home
      args:
        removes: /tmp/node_exporter*

    - name: Create Node Exporter service file
      template:
        src: ./templates/node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
      notify: Reload systemd

    - name: Run Node Exporter directly
      command: /usr/local/bin/node_exporter
      async: 1
      poll: 0

    - name: Start and enable Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes
  handlers:
    - name: Reload systemd 
      systemd:
        daemon_reload: yes
